# Executes commands at the start of an interactive session.
#
# Authors:
#	  Fullchee Zhang <fullchee@gmail.com>

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Unset manpath so we can inherit from /etc/manpath via the `manpath` command
unset MANPATH # delete if you already modified MANPATH elsewhere in your config
export MANPATH="$NPM_PACKAGES/share/man:$(manpath)"

export PATH="/usr/local/sbin:/usr/local/bin:$PATH"
export PATH="$PATH:$HOME/.local/bin"

source $HOME/.dotfiles/file-scripts.sh
