# Executes commands at the start of an interactive session.
#
# Authors:
#	  Fullchee Zhang <fullchee@gmail.com>

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

export PATH="/usr/local/sbin:/usr/local/bin:$PATH"

source $HOME/.dotfiles/file-scripts.sh
